# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  auto_review:
    base_branches: [".*"]
    drafts: true
  path_filters:
    - "!assets/js/**"
    - "!lib/hologram/**"
    - "!test/elixir/**"
    - "!test/features/**"
    - "!scripts/identifier_tokenizer/**"
  poem: false
